apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    name: web-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-server-pod
  template:
    metadata:
      name: web-server-pod
      labels:
        name: web-server-pod
    spec:
      containers:
      - image: enes789/web-server:latest
        name: web-server
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-admin-password
        envFrom:
        - configMapRef:
            name: servers-configmap
        ports: 
        - containerPort: 80

                      