apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
        app: todoapp
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        env:
        - name: MYSQL_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: MYSQL_DATABASE_DB
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: dbname
        ports: 
        - name: mysql
          containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /data/db
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
                      