apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result
    app: todoapp
spec:
  selector:
    name: result-server 
  type: NodePort
  ports:
   - name: http
     port: 30002
     targetPort: 80
     protocol: TCP
