version: '3.9'
services:
  web:
    container_name: web-server
    build: .
    restart: always
    ports:
      - '80:80'
    networks: 
      - project2

  database:
    container_name: db-server
    image: mysql:8.0.19
    restart: always
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=Clarusway_1
      - MYSQL_USER=clarusway
      - MYSQL_PASSWORD=Clarusway_1
      - MYSQL_DATABASE=bookstore_db
    networks: 
      - project2
      
networks: 
  project2: