version: '3.7'

services:
  database:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: Clarusway_1
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
      MYSQL_DATABASE: bookstore_db
    networks:
        - clarusnet

  myapp:
    image: enes/bookstore-api:latest 
    depends_on: 
      - database
    restart: always
    ports:
      - "80:80"
    networks:
      - clarusnet

networks:
    clarusnet:
        driver: bridge
